local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/pr0phecydc/WhiteCloud/main/Library.lua"))()

local Window = Library:CreateWindow("Testing Library")

local Tab = Window:CreateTab("14750528362")

Tab:CreateLabel("Label!")
Tab:CreateButton("Button!",function()
	print("Button Works!")
end)
Tab:CreateToggle("Toggle!",function(state)
	print(state)
end)
Tab1:CreateSlider("Slider!",250,function(value)
	print(value)
end)
Tab:CreateDropdown("Dropdown!",{"1","2","3"},function(selected)
	print(selected)
end)
Tab:CreateBox("Box!",function(input)
	print(input)
end)
